# Nome da Aplicação
spring.application.name=factory-optimizer

# ATIVAÇÃO DO H2 (Resolve o erro 404)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# CONFIGURAÇÃO DO BANCO (Precisa ser idêntico ao que você digita no login)
spring.datasource.url=jdbc:h2:mem:factorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# PERMISSÕES DE FRAME (Necessário para o console abrir dentro do navegador)
spring.jpa.hibernate.ddl-auto=update
spring.headers.frame-options=sameorigins